### ISSUE TITLE
Use major version (e.g. @v2 instead of @v2.1.1)

### ISSUE THREAD

**Issue by JPHutchins** [sigstore/gh-action-sigstore-python#141]
**Description**

Many of MS's official actions allow a syntax wherein
```yaml
uses: actions/upload-artifact@v4
```
*appears to get the latest version 4 feature/fix* version but never upgrades to a breaking v5, for example.

Presently this action does not allow
```yaml
uses: sigstore/gh-action-sigstore-python@v2
```

I found this doc: https://docs.github.com/en/actions/creating-actions/about-custom-actions#using-release-management-for-actions

But I'm having a hard time confirming the behavior that I assume: `@v<MAJOR>` means get the latest major version.

I see what I think is an implementation example from pypa.  Looks like a `release/v<MAJOR>` branch is created and `v<MAJOR>.<MINOR>.<PATCH>` branches get merged into it.  That's a bit more manual and error prone than I expected, but I guess it's explicit at least!

https://github.com/pypa/gh-action-pypi-publish/branches/all

**Comment by woodruffw** [comment]
Thanks for the report @JPHutchins!

Yeah, the implementation mess behind this is the main reason I haven't done it :slightly_smiling_face: -- the two ways that GitHub allows for a "major" reference like this are:

1. Create a `v2` tag, and force-push to it every time a release on `2.x.y` is made;
2. Create a `release/v2` or similar branch, and either make it the default branch *or* update it with each change to `main`.

(1) breaks tag immutability and (2) results in a more complicated merge workflow, so I've been avoiding doing either.

It's not a perfect substitute, but have you considered using [Dependabot](https://docs.github.com/en/code-security/getting-started/dependabot-quickstart-guide) to manage your GitHub Action updates?

That's what I do for most of my repos -- instead of using the (secretly mutable) `@v2` or whatever tag, I pin to the exact release tag and Dependabot sends me a PR whenever a new version is added, e.g. https://github.com/di/id/pull/224. The advantage to that is that it keeps everything precisely pinned, although at the cost of yet another piece of background CI state.

If using Dependabot would work for you, then I'm inclined to keep the status quo here and avoid mutable tags. But if it doesn't, I can look into a `v2` tag that'll track the current release series.

**Comment by JPHutchins** [comment]
Thanks for the Dependabot ideas, I'll try that out!

No desire to encourage anyone to create "faux tag moving branches".
