### ISSUE TITLE
ModuleNotFoundError: No module named 'sigstore_rekor_types'

### ISSUE THREAD

**Issue by mnot** [sigstore/gh-action-sigstore-python#94]
**Description**

The action has suddenly begun failing; it worked (in the same repo) three hours ago, but now I get:

>  ModuleNotFoundError: No module named 'sigstore_rekor_types'

**Version**

2.1.0

See debug log at: 
  https://github.com/mnot/httplint/actions/runs/7191098801/job/19585432188

**Comment by woodruffw** [comment]
Subdependency hell, sorry about that. Fixing now. Thank you for the report!

**Comment by woodruffw** [comment]
@mnot I've opened #95 for this. Would you be able to give the changes in that PR a try?

**Comment by mnot** [comment]
Not easily, unfortunately.

**Comment by woodruffw** [comment]
That's fair. I believe that fix is right, but I'll need another maintainer to approve it before I can merge it.

In the mean time, the proximate cause here is my own foolishness in releasing an incompatible version of `sigstore-rekor-types`. I'll see about yanking that version, so that actions continue to resolve the previous version instead.

**Comment by woodruffw** [comment]
Okay, the offending version has been yanked. If you re-run your failing workflow, everything *should* work again.

**Comment by mnot** [comment]
Thanks!

**Comment by woodruffw** [comment]
Thank you as well! My sincere apologies for the breakage here.
